### ISSUE TITLE
Require minimal oauth scopes

### ISSUE THREAD

**Issue by heathd** [RoryMalcolm/pay-dependabot-stats#6]
There have been security issues where apps have been setup with a github API token with `repo` scope. Such tokens give write access to private repositories. Github's permissions model is quite limited -- it's not possible to give read access to private repos without this.

Suggest that the app should refuse to start up if the API token has `repo` scope, to avoid people inadvertently giving it more permissions than needed.

**Comment by rorymalcolm** [comment]
Agreed, I am building a solution to prevent this from happening here https://github.com/alphagov/pay-dependabot-stats/pull/8
